# Generated by Django 3.0.6 on 2020-05-21 23:28

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name_plural': 'Залы'},
        ),
        migrations.AddField(
            model_name='hall',
            name='hall_slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, default=None, editable=False, populate_from='name', verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hall',
            name='height',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Длина зала %'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название зала'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='width',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Ширина зала %'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.IntegerField(choices=[(1, 'Прямоугольный'), (2, 'Овальный')], verbose_name='Тип стола')),
                ('number', models.IntegerField(verbose_name='Номер стола')),
                ('seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Количество мест')),
                ('width', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Ширина стола (м)')),
                ('height', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Длина стола (м)')),
                ('coordinate_x', models.PositiveSmallIntegerField(default=0, verbose_name='Расположение по оси X')),
                ('coordinate_y', models.PositiveSmallIntegerField(default=0, verbose_name='Расположение по оси Y')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name_plural': 'Столы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(verbose_name='Дата заказа')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurant.Hall', verbose_name='Зал')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_table', to='restaurant.Table', verbose_name='Столик')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
                'unique_together': {('table', 'date')},
            },
        ),
    ]
