# Generated by Django 3.0.6 on 2020-05-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200522_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Номер стола'),
        ),
    ]
